### ISSUE TITLE
Add contact us widget

### ISSUE THREAD

**Issue by caseywebdev** [orgsync/orgsync-widgets#15]

**Comment by justinsteffy** [comment]
I'm not sure this can be a widget with an exposed api.  It is basically a captcha protected form that sends emails to all the core members of group.  If we open this up in the api, it could easily be abused...  I think this will have to be a special case where the website builder uses some private api (or elastic search or something).

**Comment by amirrajan** [comment]
Another set of notifications I'm getting. I miss y'all already! (Except Tyler)

**Comment by clifton** [comment]
Unsubscribe from our repos then :)
