### ISSUE TITLE
Browse Orgs Set Height Issue?

### ISSUE THREAD

**Issue by matttarantino** [orgsync/orgsync-widgets#46]
I added the browse orgs widget on Scranton's site (clubs.scranton.edu) and noticed that when you filter by certain categories, there is a set height on the list. Is this a bug? I currently have some extra margin on the bottom to keep that from happening. 

See below:

(All orgs, no category)
<img width="1281" alt="screen shot 2016-02-12 at 2 07 45 pm" src="https://cloud.githubusercontent.com/assets/5056389/13019065/b650f3e6-d192-11e5-9232-5391b29b5ca3.png">

(selected category)
![screen shot 2016-02-12 at 2 08 12 pm](https://cloud.githubusercontent.com/assets/5056389/13019189/78c1d2d8-d193-11e5-9e51-a1e8cf713fb7.png)

I remove the set height and it looks okay. 

@caseywebdev

**Comment by caseywebdev** [comment]
This repo is dead, but I fixed this in [react-list](https://github.com/orgsync/react-list/commit/d746ade165b0b9ea0164af3be79e1854ac78005d).

**Comment by caseywebdev** [comment]
Fixed in production.

**Comment by matttarantino** [comment]
Thanks @caseywebdev . Looks great
